language: python
python:
- '3.4'
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- coverage run --source=foia_hub manage.py test --settings=foia_hub.settings.test
- flake8 . --ignore=E501,E302,E303,E123 --exclude=foia_hub/settings,docs/source
- flake8 foia_hub/settings --ignore=F403,E501,E302,E303,E123
after_success:
- coveralls
notifications:
  webhooks: http://project-monitor.cf.18f.us/projects/foia-hub/status
