language: python
python:
  - "3.4"
install:
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements-dev.txt
script:
  - coverage run --source=foia_hub manage.py test --settings=foia_hub.settings.test

  # ignore:
  # * E501 - line length limit
  # * E302,E303 - too many blank lines (come on)
  # * E123 - indentation on data structures (very restrictive)
  - flake8 . --ignore E501,E302,E303,E123 --exclude foia_hub/settings,docs/source

  # * F403 - "import *"
  - flake8 foia_hub/settings --ignore F403,E501,E302,E303,E123
after_success:
  - coveralls
